# SQL challenge Famous Paintings
Idea taken from [techTFQ's youtube video](https://techtfq.com/blog/sql-project-sql-case-study-to-solve-and-practice-sql-queries)  
[Kaggle's dataset link](https://www.kaggle.com/datasets/mexwell/famous-paintings)

This notebook carries out the cleaning process of the datasets downloaded from the kaggle repository.

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
root = os.getcwd()

# create a directory for the clean CSV files
os.makedirs(f'{root}/clean_csv_datasets', exist_ok=True)

# change to csv folder
os.chdir(f'{root}/csv_datasets')

# print the current working directory to check if we are in the right place
os.getcwd()

'/workspaces/SQL_challenge_paintings/csv_datasets'

List the csv files available

In [3]:
print([i for i in os.listdir() if i.endswith('.csv')], sep = ', ')

['canvas_size.csv', 'image_link.csv', 'museum.csv', 'artist.csv', 'subject.csv', 'museum_hours.csv', 'product_size.csv', 'work.csv']

# Cleaning of the datasets

## `work` dataset

In [4]:
work = pd.read_csv('work.csv')

In [5]:
work.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14776 entries, 0 to 14775
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   work_id    14776 non-null  int64
 1   name       14776 non-null  object
 2   artist_id  14776 non-null  int64
 3   style      13490 non-null  object
 4   museum_id  4553 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 577.3+ KB

### missing values

In [6]:
work.isna().sum()

work_id          0
name             0
artist_id        0
style         1286
museum_id    10223
dtype: int64

10223 paintings don't have an associated museum.

### duplicates

In [7]:
work.duplicated().sum()

np.int64(60)

In [8]:
work[work.duplicated(keep=False)].sort_values('work_id')

,work_id,name,artist_id,style,museum_id
1135,122662,The Dunes at Camiers,862,Realism,NaN
11103,122662,The Dunes at Camiers,862,Realism,NaN
11061,122691,Landscape with a Sunlit Stream,862,Realism,NaN
1130,122691,Landscape with a Sunlit Stream,862,Realism,NaN
5878,181318,"Maroon, Pink and Shade of Red",770,NaN,NaN
...,...,...,...,...,...
5877,181925,Light Blue and Pink,770,NaN,NaN
5897,181932,"Purple, White Stripe on Soft Orange",770,NaN,NaN
12233,181932,"Purple, White Stripe on Soft Orange",770,NaN,NaN
5859,181941,"Blue Stripe, Orange Shades",770,NaN,NaN
12194,181941,"Blue Stripe, Orange Shades",770,NaN,NaN

In [9]:
work = work.drop_duplicates()

In [10]:
work.duplicated().sum()

np.int64(0)

### check work_id

In [11]:
work.work_id.agg(['count', 'min', 'max'])

count     14716
min         178
max      209770
Name: work_id, dtype: int64

I can't reassign the `work_id` values, since they are foreign keys in other tables.

### dtypes

In [12]:
work.dtypes

work_id        int64
name          object
artist_id      int64
style         object
museum_id    float64
dtype: object

### unique values

In [13]:
work['style'].unique()

array(['Baroque', nan, 'Neo-Classicism', 'Renaissance', 'Expressionism',
       'American Landscape', 'Post-Impressionism', 'Classicism',
       'Avant-Garde', 'Impressionism', 'Cubism', 'Rococo', 'Realism',
       'Fauvism', 'Nabi', 'Symbolism', 'Naturalism', 'American Art',
       'Romanticism', 'Orientalism', 'Art Nouveau', 'Surrealism',
       'Pointillism', 'Japanese Art'], dtype=object)

In [14]:
work.museum_id.nunique()

57

There should be 57 different museums in the `museum` table.

### Export `work` dataset

In [ ]:
work.to_csv('../clean_csv_datasets/work.csv', index = False, na_rep='NULL')

## `artist` dataset

In [16]:
artist = pd.read_csv('artist.csv')

In [17]:
artist.head()

,artist_id,full_name,first_name,middle_names,last_name,nationality,style,birth,death
0,500,Pierre-Auguste Renoir,Pierre,Auguste,Renoir,French,Impressionist,1841,1919
1,501,Alexandre Cabanel,Alexandre,NaN,Cabanel,French,Classicist,1823,1889
2,502,James Ensor,James,NaN,Ensor,Belgian,Expressionist,1860,1949
3,503,Maximilien Luce,Maximilien,NaN,Luce,French,Pointillist,1858,1941
4,504,August Macke,August,NaN,Macke,German,Expressionist,1887,1914

### missing values

In [18]:
artist.isna().sum()

artist_id         0
full_name         0
first_name        0
middle_names    273
last_name         0
nationality       0
style             0
birth             0
death             0
dtype: int64

### duplicates

In [19]:
artist.duplicated().sum()

np.int64(0)

### dtypes

In [20]:
artist.dtypes

artist_id        int64
full_name       object
first_name      object
middle_names    object
last_name       object
nationality     object
style           object
birth            int64
death            int64
dtype: object

### Export `artist` dataset

In [ ]:
artist.to_csv('../clean_csv_datasets/artist.csv', index = False, na_rep='NULL')

## `subject` dataset

In [22]:
subject = pd.read_csv('subject.csv')

In [23]:
subject.head()

   work_id     subject
0   160228  Still-Life
1   160236  Still-Life
2   160244  Still-Life
3   160252  Still-Life
4   160260  Still-Life

### missing values

In [24]:
subject.isna().sum()

work_id    0
subject    0
dtype: int64

### duplicates

In [25]:
subject.duplicated().sum()

np.int64(59)

In [26]:
subject[subject.duplicated(keep=False)].sort_values('work_id')

      work_id              subject
619    122662            Seascapes
5365   122662            Seascapes
2827   181318  Abstract/Modern Art
5790   181318  Abstract/Modern Art
5768   181331  Abstract/Modern Art
...       ...                  ...
5789   181925  Abstract/Modern Art
2846   181932  Abstract/Modern Art
5809   181932  Abstract/Modern Art
2808   181941  Abstract/Modern Art
5770   181941  Abstract/Modern Art

[117 rows x 2 columns]

### remove duplicates

In [27]:
subject = subject.drop_duplicates()

### Export `subject` dataset

In [ ]:
subject.to_csv('../clean_csv_datasets/subject.csv', index = False, na_rep='NULL')

## `canvas_size` dataset

In [29]:
canvas_size = pd.read_csv('canvas_size.csv')

In [30]:
canvas_size.head()

   size_id  width  height          label
0       20     20     NaN  20" Long Edge
1       24     24     NaN  24" Long Edge
2       30     30     NaN  30" Long Edge
3       36     36     NaN  36" Long Edge
4       40     40     NaN  40" Long Edge

### missing values

In [31]:
canvas_size.isna().sum()

size_id    0
width      0
height     7
label      0
dtype: int64

### duplicates

In [32]:
canvas_size.duplicated().sum()

np.int64(0)

### dtypes

In [33]:
canvas_size.dtypes

size_id      int64
width        int64
height     float64
label       object
dtype: object

### `canvas_size` unique values

In [34]:
canvas_size.size_id.unique()

array([  20,   24,   30,   36,   40,   48,   56, 1522, 1618, 1620, 1623,
       1624, 1632, 1826, 1926, 1929, 2016, 2020, 2024, 2029, 2030, 2040,
       2126, 2129, 2130, 2136, 2219, 2225, 2226, 2227, 2230, 2244, 2332,
       2416, 2418, 2420, 2424, 2428, 2429, 2430, 2432, 2436, 2440, 2448,
       2519, 2520, 2522, 2529, 2530, 2531, 2532, 2619, 2620, 2621, 2632,
       2636, 2637, 2639, 2640, 2726, 2733, 2735, 2823, 2922, 2923, 2924,
       2925, 2936, 2937, 2938, 2939, 3020, 3024, 3030, 3034, 3037, 3040,
       3046, 3060, 3124, 3125, 3216, 3218, 3223, 3224, 3225, 3226, 3232,
       3235, 3239, 3240, 3242, 3244, 3246, 3251, 3324, 3326, 3528, 3537,
       3538, 3541, 3545, 3546, 3622, 3624, 3626, 3627, 3628, 3629, 3632,
       3636, 3637, 3643, 3648, 3652, 3654, 3672, 3726, 3728, 3729, 3730,
       3732, 3735, 3830, 3847, 3851, 3926, 3929, 3931, 3932, 3934, 3935,
       3939, 3979, 4020, 4024, 4026, 4030, 4032, 4040, 4060, 4080, 4120,
       4130, 4236, 4352, 4382, 4430, 4434, 4532, 4534, 4630, 4635, 4636,
       4639, 4739, 4824, 4836, 4848, 4860, 4872, 4896, 5063, 5065, 5135,
       5137, 5138, 5139, 5264, 5429, 5436, 5439, 5468, 5648, 5691, 5842,
       5845, 5936, 6030, 6040, 6048, 6060, 6451, 6765, 6854, 6951, 6952,
       6961, 7048, 7171, 7236, 7248, 7761, 7940, 7955, 7963, 8040, 8051,
       8959, 9648])

In [35]:
canvas_size.size_id.agg(['min', 'max'])

min      20
max    9648
Name: size_id, dtype: int64

### Export `canvas_size` dataset

In [ ]:
canvas_size.to_csv('../clean_csv_datasets/canvas_size.csv', index = False, na_rep='NULL')

## `product_size` dataset

In [37]:
product_size = pd.read_csv('product_size.csv')

In [38]:
product_size.head()

   work_id size_id  sale_price  regular_price
0   160228      24          85             85
1   160228      30          95             95
2   160236      24          85             85
3   160236      30          95             95
4   160244      24          85             85

### missing values

In [39]:
product_size.isna().sum()

work_id          0
size_id          0
sale_price       0
regular_price    0
dtype: int64

### duplicates

In [40]:
product_size.duplicated().sum()

np.int64(687)

In [41]:
product_size[product_size.duplicated(keep = False)].sort_values(['work_id', 'size_id'])

     work_id size_id  sale_price  regular_price
28     23448      20          75             75
494    23448      20          75             75
29     23448      24          85             85
495    23448      24          85             85
30     23448      30          95             95
..       ...     ...         ...            ...
930   194176      30          95             95
465   194176      36         125            125
931   194176      36         125            125
463   194176      40         145            145
929   194176      40         145            145

[1373 rows x 4 columns]

### drop duplicates

In [42]:
product_size = product_size.drop_duplicates()

### dtypes

In [43]:
product_size.dtypes

work_id           int64
size_id          object
sale_price        int64
regular_price     int64
dtype: object

`size_id` appears with object dtype. It must be due to missing values for `size_id`

In [44]:
product_size.size_id.unique()

array(['24', '30', '3024', '3226', '3629', '4030', '4836', '6048', '6854',
       '3624', '4630', '5436', '6040', '7248', '20', '2430', '2632',
       '2936', '3040', '3648', '4860', '5468', '36', '2436', '3046',
       '3654', '4060', '4872', '1620', '2024', '1624', '2030', '40', '48',
       '4020', '4824', '6030', '7236', '8040', '9648', '2424', '3030',
       '3636', '4040', '4848', '6060', '2016', '2420', '2020', '2416',
       '3020', '#VALUE!', '1632', '2040', '2448', '3060', '3672', '4080',
       '16.223', '28.836', '39.532', '3216', '56', '3628.7', '32.226',
       '3225.5', '4896', '3218', '32.426', '3239.8', '2936.5', '3225.6',
       '3223.7', '36.329', '36.432', '36.532', '27.326', '31.944',
       '28.525', '3232', '57.745', '4434', '3225.9', '2417.8', '7171',
       '5136.5', '5439.4', '22.43', '26.232', '2429', '50.635', '39.632',
       '3225.8', '3730', '3627', '35.652', '4235.5', '5062.6', '2823.2',
       '2419.7', '25.632', '37.428', '2921.7', '2921.5', '2639.8',
       '32.251', '31.525', '5936.2', '2923.6', '2923.7', '25.732',
       '2632.1', '57.542', '3536.5', '38.531', '5691.2', '3225.7',
       '32.326', '39.526', '23.529', '4023.7', '36.429', '36.326',
       '36.829', '32.524', '36.529', '39.435', '79.163', '36.626',
       '3239.4', '39.429', '5844.9', '3239.2', '57.545', '25.832',
       '32.332', '28.824', '3628.6', '4635.4', '4635', '2632.3', '50.465',
       '4835.8', '19.524', '28.936', '3246', '3628.5', '44.534', '3628.8',
       '45.835', '28.537', '32.126', '28.724', '3729.3', '37.53',
       '29.137', '3527.6', '2227.2', '4532', '3123.6', '3729.9', '26.332',
       '2936.6', '35.628'], dtype=object)

There are some value that don't make sense, since they have decimal places. Other values are `#VALUE!`. Let's check what percentage the wrong values make out of the total dataset.

In [45]:
(round( product_size[product_size.size_id.str.contains('.', regex = False)]
       .shape[0] / product_size.shape[0] * 100, 3) )

0.106

In [46]:
round( product_size[product_size.size_id == '#VALUE!']
      .shape[0] / product_size.shape[0] * 100, 3)

0.193

In [47]:
anomalous_size_id_records = product_size[(product_size.size_id == "#VALUE!") | 
                                         (product_size.size_id.str.contains('.', regex = False))]

round( anomalous_size_id_records.shape[0] / product_size.shape[0] * 100, 3)

0.299

Since the records in `product_size` dataset which have anomalous values for `size_id` (`#VALUE!` or decimal values) don't make up more than 0.3% of the total dataset, the easiest and quickest way of dealing with them is to remove them. The time spent trying to figure out how to clean this values is not worth.

In [48]:
product_size.loc[anomalous_size_id_records.index, 'size_id'] = np.nan

In [49]:
product_size.isna().sum()

work_id            0
size_id          328
sale_price         0
regular_price      0
dtype: int64

After cleaning and removing the anomalous values, I will convert the `size_id` column to `float` dtype.

In [50]:
product_size.loc[:, 'size_id'] = product_size.size_id.astype('float')

Now, I want to check if there are any records whose `size_id` value don't have a match in the `size_id` column from the `canvas_size` dataset.

In [51]:
canvas = pd.read_csv('canvas_size.csv')

I will left merge the `product_size` dataset with the `canvas_size`, using `size_id` as key column. If there were any record with a `size_id` which doesn't exist in the `canvas_size` dataset, their `width` values would be `NaN`.

In [52]:
prod_canvas_merged = product_size.dropna(subset='size_id').merge(canvas, how = 'left', on = 'size_id')

In [53]:
prod_canvas_merged.width.isna().sum()

np.int64(0)

Finally, I can say that the cleaning process of `product_size` dataset is finished.

### Export `product_size` dataset

In [ ]:
product_size.to_csv('../clean_csv_datasets/product_size.csv', index = False, na_rep='NULL')

## `museum` dataset

In [55]:
museum = pd.read_csv('museum.csv')

In [56]:
museum.head().T

,0,1,2,3,4
museum_id,30,31,32,33,34
name,The Museum of Modern Art,Pushkin State Museum of Fine Arts,National Gallery of Victoria,São Paulo Museum of Art,The State Hermitage Museum
address,11 W 53rd St,12 Ulitsa Volkhonka,180 St Kilda Rd,"Av. Paulista, 1578 - Bela Vista",Palace Square
city,New York,Moscow,Melbourne,São Paulo,2
state,NY,NaN,Victoria,NaN,Sankt-Peterburg
postal,10019,119019,3004,01310-200,190000
country,USA,Russia,Australia,Brazil,Russia
phone,+1 212 708-9400,+7 495 697-95-78,+61 (0)3 8620 2222,+55 11 3149-5959,7 812 710-90-79
url,https://www.moma.org/,https://pushkinmuseum.art/,https://www.ngv.vic.gov.au/,https://masp.org.br/,https://www.hermitagemuseum.org/wps/portal/her...

### dtypes

In [57]:
museum.dtypes

museum_id     int64
name         object
address      object
city         object
state        object
postal       object
country      object
phone        object
url          object
dtype: object

### missing values

In [58]:
museum.isna().sum()

museum_id     0
name          0
address       0
city          0
state        19
postal        7
country       0
phone         0
url           0
dtype: int64

I will have a look at the url addresses.

In [59]:
museum.url.sample(10)

15            https://www.kunsthaus.ch/en/
49       https://www.nasjonalmuseet.no/en/
48    https://www.liverpoolmuseums.org.uk/
56                https://courtauld.ac.uk/
21       https://www.barnesfoundation.org/
51      https://www.kunstmuseumbern.ch/en/
44             https://krollermuller.nl/en
8       https://www.mbaq.fr/en/home-3.html
1               https://pushkinmuseum.art/
41             https://www.ohara.or.jp/en/
Name: url, dtype: object

### duplicates

In [60]:
museum.duplicated().sum()

np.int64(0)

### Export `museum` dataset

In [ ]:
museum.to_csv('../clean_csv_datasets/museum.csv', index = False, na_rep='NULL')

## `museum_hours` dataset

In [20]:
museum_hours = pd.read_csv('museum_hours.csv')

In [21]:
museum_hours.head()

   museum_id        day      open     close
0         30     Sunday  10:30:AM  05:30:PM
1         30     Monday  10:30:AM  05:30:PM
2         30    Tuesday  10:30:AM  05:30:PM
3         30  Wednesday  10:30:AM  05:30:PM
4         30    Thusday  10:30:AM  05:30:PM

### dtypes

In [64]:
museum_hours.dtypes

museum_id     int64
day          object
open         object
close        object
dtype: object

### unique values

In [65]:
museum_hours.day.unique()

array(['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thusday', 'Friday',
       'Saturday', 'Thursday'], dtype=object)

In [66]:
museum_hours.open.unique()

array(['10:30:AM', '11:00:AM', '10:00:AM', '09:30:AM', '09:00:AM',
       '04:00:PM', '01:00:PM', '12:30:PM', '11:30:AM', '08:15:AM',
       '12:00:PM'], dtype=object)

In [67]:
museum_hours.close.unique()

array(['05:30:PM', '07:00:PM', '06:00:PM', '05:00:PM', '08:00:PM',
       '09:00:PM', '06:30:PM', '09:45:PM', '02:00:PM', '04:00:PM',
       '05:15:PM', '08:45:PM', '04:30:PM', '03:30:PM', '08 :00:PM'],
      dtype=object)

### Fix bad formated values (`08 :00:PM`)

In [22]:
museum_hours.loc[museum_hours.close == '08 :00:PM', 'close'] = '08:00:PM'

In [23]:
museum_hours.close.unique()

array(['05:30:PM', '07:00:PM', '06:00:PM', '05:00:PM', '08:00:PM',
       '09:00:PM', '06:30:PM', '09:45:PM', '02:00:PM', '04:00:PM',
       '05:15:PM', '08:45:PM', '04:30:PM', '03:30:PM'], dtype=object)

### conversion of opening and closing hours from **AM / PM** format into **24H** format.

For the times using *PM*, I will add 12 hours to the hour number.

In [28]:
def clean_hours(time_str):
    hour = time_str[:2]
    minutes = time_str[3:5]
    day_period = time_str[-2:]

    if day_period == 'PM':
        clean_time = f'{int(hour) + 12:02}:{minutes}'
    elif day_period == 'AM':
        clean_time = hour + ':' + minutes

    return clean_time

In [32]:
museum_hours.open.sample(5)

224    11:30:AM
24     10:00:AM
187    11:00:AM
154    11:00:AM
11     11:00:AM
Name: open, dtype: object

In [33]:
museum_hours.close.sample(5)

18     05:00:PM
280    05:00:PM
127    07:00:PM
291    09:00:PM
160    05:30:PM
Name: close, dtype: object

Clean the hours

In [34]:
museum_hours.loc[:, 'open'] = museum_hours.open.apply(clean_hours)
museum_hours.loc[:, 'close'] = museum_hours.close.apply(clean_hours)

In [35]:
museum_hours.sample(5)

     museum_id        day   open  close
54          38   Thursday  09:30  17:30
345         86     Monday  10:00  18:00
67          40   Saturday  09:00  18:00
36          35  Wednesday  10:00  17:00
231         67     Sunday  10:00  17:00

In [36]:
museum_hours.dtypes

museum_id     int64
day          object
open         object
close        object
dtype: object

### duplicates

In [37]:
museum_hours.duplicated().sum()

np.int64(1)

In [38]:
museum_hours[museum_hours.duplicated(keep = False)]

     museum_id       day   open  close
311         80  Saturday  11:00  17:00
312         80  Saturday  11:00  17:00

In [39]:
museum_hours = museum_hours.drop_duplicates()

### missing values

In [40]:
museum_hours.isna().sum()

museum_id    0
day          0
open         0
close        0
dtype: int64

### Export `museum_hours` dataset

In [41]:
museum_hours.to_csv('../clean_csv_datasets/museum_hours.csv', index = False, na_rep='NULL')

## `image_link` dataset

In [78]:
image_link = pd.read_csv('image_link.csv')

In [79]:
image_link.head()

,work_id,url,thumbnail_small_url,thumbnail_large_url
0,181978,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
1,173188,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
2,194065,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
3,129337,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
4,141073,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...

### dtypes

In [80]:
image_link.dtypes

work_id                 int64
url                    object
thumbnail_small_url    object
thumbnail_large_url    object
dtype: object

### missing values

In [81]:
image_link.isna().sum()

work_id                0
url                    0
thumbnail_small_url    2
thumbnail_large_url    2
dtype: int64

In [82]:
image_link.fillna('Link not available', inplace = True)

### duplicates

In [83]:
image_link.duplicated().sum()

np.int64(60)

In [84]:
image_link[image_link.duplicated(keep = False)].sort_values('work_id')

,work_id,url,thumbnail_small_url,thumbnail_large_url
531,122662,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
3333,122662,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
927,122691,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
4315,122691,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
4350,181318,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
...,...,...,...,...
7350,181925,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
9528,181932,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
13886,181932,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
9568,181941,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...
12370,181941,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...,https://v5.airtableusercontent.com/v1/15/15/16...

In [85]:
image_link.drop_duplicates(inplace = True)

### Export `image_link` dataset

In [ ]:
image_link.to_csv('../clean_csv_datasets/image_link.csv', index = False)